---
format: 
  live-html:
    toc: true

execute:
  echo: false
  warning: false
  message: false

embed-resources: true

filters:
  - custom-numbered-blocks

custom-numbered-blocks:
  classes:
    Assumption:
      colors: [FFCDD2, F44336]
      boxstyle: foldbox.simple
      collapse: false
      numbered: false
    Example:
      colors: [BBDEFB, 2196F3]
      boxstyle: foldbox.simple
      collapse: false
    Exercise:
      colors: [C8E6C9, 4CAF50]
      boxstyle: foldbox.simple
      collapse: false
    Note:
      colors: [FFF9C4, FFEB3B]
      boxstyle: foldbox.simple
      collapse: false
      numbered: false
    Key-point:
      colors: [FFF9C4, FFEB3B]
      boxstyle: foldbox.simple
      collapse: false
      numbered: false
webr:
  render-df: gt-interactive

resources:
  - Data
---
{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ./_extensions/r-wasm/live/_gradethis.qmd >}}

```{webr}
#| include: false
library(tidyverse)
library(plotly)
theme_set(theme_bw())
```

```{r}
#| include: false
library(tidyverse)
theme_set(theme_bw())
```

# Multiple Linear Regression (MLR)

Most practical applications of linear regression require models more complex than the simple linear regression(SLR) model introduced in @sec-simple_linear_model.  Multiple linear regression (MLR) extends simple linear regression by allowing $Y$ to depend on more than one predictor variable. This enables richer models and allows us to estimate the *partial* contribution of each predictor while accounting for others.

- [ ] Continue

## When to extend SLR

SLR is limited to one predictor. MLR becomes appropriate when:

* Multiple factors plausibly influence the response.
* Excluding predictors may bias results.
* You wish to measure the unique contribution of each predictor while controlling for others.

::: Example
### Advertising sales
Lets consider a simple example using the `Advertising` dataset
```{webr}
#| edit: false
ads <- read.csv("Data/Advertising.csv")
```
Suppose that we are statistical consultants hired by a client to investigate the association between advertising and sales of a particular product. The `Advertising` dataset (which we have imported as `ads`) consists of the sales of that product in 200 different markets, along with advertising budgets for the product in each of those markets for two different media: TV, and radio. [^1]

```{webr}
#| edit: false
ads
```

[^1]: This exmple is adapted from "Introduction to Statistical Learning (2)" - an excellent (and freely available) text on statistical modelling.  

We might look at each bivariate (i.e. two variables) relationship between sales and advertising expendature separately:

:::: {.panel-tabset}
### $Sales \sim TV$
```{webr}
#| edit: false
#| echo: false
ggplot(ads, aes(x = TV, y = Sales)) +
  geom_point() +
  labs(x = "TV", y = "Sales")
```
### $Sales\sim Radio$
```{webr}
#| edit: false
#| echo: false
ggplot(ads, aes(x = Radio, y = Sales)) +
  geom_point() +
  labs(x = "Radio", y = "Sales")
```
::::

However we might also look at the *multivariate* relationship:

:::: {.panel-tabset}
### Coloured Scatter
Here we encode the values of the second predictor (`Radio`) with colour
```{webr}
#| edit: false
#| echo: false
ggplot(ads, aes(x = TV, y = Sales, colour = Radio)) +
  geom_point() +
  scale_colour_viridis_c() +
  labs(x = "TV", y = "Sales", colour = "Radio")
```
### 3-D Scatter
In the case of 3 variables we can also extend our visualisation to 3 dimensions
```{webr}
#| edit: false
#| echo: false
plot_ly(ads, x = ~TV, y = ~Radio, z = ~Sales,
        type = "scatter3d", mode = "markers", showlegend=FALSE)
```
::::
Using multiple predictors simultaneously gives us more information than using each variable separately - this is a great case for applying multiple regression!
:::

- [ ] Continue

## The multiple linear regression model

The multiple linear model extends the simple linear model from @sec-simple_linear_model straightforwardly by adding the extra variables to the deterministic linear predictor, each with its own parameter:

::: Key-point
### The MLR model
$$
Y = \beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k + \varepsilon, \quad \varepsilon \sim N(0,\sigma^2)
$$
:::

Now, instead of a single predictor $x$, we may have several ($k$) predictors $x_1, x_2, \ldots, x_k$, each corresponding to a column in our dataset. We use an index to distinguish these predictors, and each predictor $x_i$ has a corresponding parameter $\beta_i$ governing its effect on the response. Note that we have updated the intercept parameter $\alpha$ from the simple linear regression section to $\beta_0$, because it is simply another parameter in the model!

The random error term, $\varepsilon$, stays the same, so the assumptions of MLR are very similar to those of SLR:

::: Assumption
### Assumptions of the MLR model
- A *linear* predictor, e.g. $E[Y]=\beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k$. 
- *Independent* and identically distributed random error terms that
  - Have a mean $\mu=0$, and a constant variance $Var(\varepsilon)=\sigma^2$
  - Follow a normal distribution: $N(0,\sigma^2)$
:::

::: Note
### Multivariate Linearity
Although this is still a *linear* model, the term "linear" no longer refers to a literal straight line in two dimensions as it did in simple linear regression. Instead, "linear" means that the model is **linear in its parameters**: each $\beta_i$ multiplies a predictor and enters additively. This linear model may live in a high-dimensional predictor space and cannot be visualised as a single line. For example, for the three dimensional data presented above (one outcome: Sales + two predictors: TV, Radio), a linear model may instead look like a *plane* - the three dimensional equivalent of a line in two dimensions.
```{webr}
#| echo: false
#| edit: false

# Fit least squares plane
fit <- lm(Sales ~ TV + Radio, data = ads)

# Create grid for the plane
tv_seq <- seq(min(ads$TV), max(ads$TV), length.out = 30)
radio_seq <- seq(min(ads$Radio), max(ads$Radio), length.out = 30)
grid   <- expand.grid(TV = tv_seq, Radio = radio_seq)
grid$sales_hat <- predict(fit, newdata = grid)

z_mat <- matrix(grid$sales_hat, nrow = length(tv_seq), ncol = length(radio_seq))

# Plotly 3D scatter + plane
fig <- plot_ly() |>
  add_surface(
    x = radio_seq,
    y = tv_seq,
    z = z_mat,
    opacity = 0.6,
    showscale = FALSE,
    name = "LS plane"
  ) |>
  layout(
    scene = list(
      xaxis = list(title = "Radio"),
      yaxis = list(title = "TV"),
      zaxis = list(title = "Sales")
    ),
    showlegend = FALSE
  ) 

fig
```

A further discussion of *linearity* will take place in @sec-non_linearity, when we discuss higher order multiple regression models. 
:::

- [ ] Continue 

## Partial Regression Coefficients, $\beta_i$
Even though our model is no longer just a straight line, the *slope* interpretation from SLR is still relevant in MLR. Now however, $\beta_i$ describes the expected change in the mean response for a one-unit increase in $x_i$, **holding all other predictors constant**. 

::: Example
#### Interpreting a partial coefficient, $\beta_i$
We may propose a model for `Sales` whereby the baseline sales (when no money is invested in advertising) is $beta_0=3$,  $\beta_{TV}= 0.1$ and $\beta_{Radio}= 0.2$, i.e. 
$$
E[Sales]= 3 + 0.1\cdot\text{TV} + 0.2\cdot \text{Radio}
$$

* A $1k increase in TV advertising expenditure is associated with an expected 100 unit (0.1*1000units - the scale of the outcome) increase in sales, holding Radio expenditure constant.
* Converely, at a fixed level of `TV` advertising expenditure, a $1k increase in Radio advertisin expenditure corresponds to an expected 200 unit increase in sales.
:::


::: Exercise
### Calculating the expected value of a multiple regression model
Given this model 
$$
E[Sales]= 3 + 0.1\cdot\text{TV} + 0.2\cdot \text{Radio}
$$
Calcultate the expected sales (in thousands of units) for 5k TV and 8k Radio advertising expenditure 

```{webr}

```
:::

### Fitting MLR Models in R and the `tidy()` function 
Fitting a multiple linear regression uses the exact same conceptual process from @sec-leastsquares: Residuals are still defined $e = Y- \hat{Y}$, and minimising the sum of squared residuals provides optimal and unique 'least squares estimates' for the model parameters $b_0, \ldots, b_k$.

MLR uses the same `lm()` function as SLR (these are both 'linear models', after all). Now, the model `formula` (the first argument, identified by the `~` separating the LHS and RHS) includes both predictors on the RHS, separated by a `+`:
```{webr}
mod <- lm(Sales ~ TV + Radio, data = ads)
```
::: Note
### R `formulas`

:::
and we can extract our model coefficients ($\beta_0, \ldots,\beta_3$) in the same way: 

::: {.panel-tabset}
#### indexing
```{webr}
#| echo: true
mod$coefficients
```
#### coef() function

```{webr}
#| echo: true
coef(mod)
```
:::

::: Exercise
## extracting coefficients from an `lm` model
Use the the least-squares coefficients from `mod` to complete these partial regression plots

```{webr}
ggplot(ads)+
  aes(x=TV, y=Sales)+
  geom_point()+
  geom_abline(intercept = mod$coefficients[1], slope = ______)
```
:::

We can also use the `tidy` function from the `broom` package for a nice summary of the relevant inferential statistics for each parameter:
```{webr}
library(broom)
tidy(mod, conf.int = TRUE)
```
The hypotheses being tested for each coefficient is analagous to that in the SLR case @sec-beta_inference:
$$
H_0 : \beta_i = 0 
\qquad\text{vs}\qquad
H_a : \beta_i \ne 0.
$$
And is tested the same way - using the t-statistic:
$$
t_i = \frac{\hat\beta_i}{\operatorname{SE}(\hat\beta_i)}.
$$

However, the interpretation of these hypotheses is slightly more nuanced. As pointed out above, the value of \beta_i here does not represent the relationship between $Y$ and $X_i$ without qualification - but only when the other variables are held constant. Analogously, the hypothesis being tested by $t_i$ is whether $X_i$ is related to to $Y$ *once the other predictors are accounted for*. 
::: Key-point
### interpreting partial regression coefficients, $\beta_i$
:::

Because of this:

- The significance of a predictor can change when variables are added or removed.
- A small p-value for $\beta_i$ suggests a meaningful **partial effect**, not necessarily a *marginal* (unadjusted) one.

### Warning: Multicollinearity
- least squares is an amazing method for fitting but it has a weakness
- correlated predictors can cause unstable parameter estimates
- Check for correlation using a correlation matrix or using `vif`
- this will be adressed more comprehensively in module 6: diagnostics an transformations. 

## Global model statistics: The F-Test and measures of model fit

Having multiple predictor variables expands the scope of the kind of questions we can ask about our linear model. Rather than looking at each coefficient separately, we can ask whether our model *as a whole* is effective in explaining the outcome $Y$ In other words, is the combined contribution of the predictors enough to conclude that a linear relationship exists?

Formally, the global hypothesis test is:

- $H_0$: all slope coefficients are zero (no linear relationship between $Y$ and the predictors)  
- $H_a$: at least one slope coefficient is non-zero (the model is useful)

This shift parallels the move from multiple t-tests to an ANOVA - instead of testing individual “effects,” we examine the overall **variance explained** by a model.

The F-statistic compares:

- **variation explained by the model** (mean regression sum of squares, MSR),  
- **residual variation** (mean squared error, MSE).

Because each of these quantities is constructed from squared normal deviations, the ratio

$$
F = \frac{\text{MSR}}{\text{MSE}}
$$

follows an F-distribution under $H_0$.  
If the model truly explains some structure in the data, MSR will be noticeably larger than MSE.

[#^1] The links between ANOVA and linear regression will be futher explored here in @sec-qualitative_predictors. 

::: Example
In the life expectancy example, the output might report

```
F-statistic: 28.2 on 4 and 44 DF,  p-value: 1.19e-11
```

The very small p-value indicates strong evidence against $H_0$. We conclude that at least one of the predictors (Population, Health, Internet, BirthRate) is useful for predicting life expectancy, and that the model is useful overall.
:::

::: Exercise
Given an F-statistic of 12.3 with p = 0.0004, state the null and alternative hypotheses and conclude whether the model is useful at the 5% level.
:::
#### global statistics with `glance()`
We can obtain the model F-statistic using the `glance()` function from the `broom` package

```{webr}
glance(mod)
```

This output includes several global model features besides the global test statistic and p-value. 

### Adjusted $R^2$

Once we have established that the model is useful overall, we can quantify *how much* of the variation in $Y$ it explains. The measure $R^2$ was introduced in SLR and extends naturally to MLR In multiple regression, $R^2$ plays the same descriptive role, but its
interpretation changes subtly because the model now includes several predictors.

### $R^2$ in Multiple Regression

We define
$$
R^2 = 1 - \frac{\text{SSE}}{\text{SST}},
$$
exactly as before. The difference lies in what $R^2$ represents:

- In SLR, $R^2$ reflects how well a *single predictor* explains variation in $Y$.
- In MLR, $R^2$ reflects the **combined explanatory power of all predictors working together**.

Because adding a new predictor can never increase SSE, it follows that **$R^2$ can never decrease when more predictors are added**, even if the new predictor has little or no real relationship with the response.
For this reason, $R^2$ is not reliable for comparing models with different numbers of predictors.

### Adjusted $R^2$

To address the fact that $R^2$ is overly optimistic in larger models, we use the *adjusted coefficient of determination*:
$$
R^2_{\text{adj}} = 1 -\frac{\text{SSE}/(n - k - 1)}{\text{SST}/(n - 1)}.
$$

Adjusted $R^2$:

- **penalises** the inclusion of additional predictors,
- increases only when a predictor provides meaningful explanatory value,
- and may decrease when a predictor contributes little or nothing.

Thus,

- **$R^2$** is appropriate as a descriptive measure of how much variation the fitted model explains,
- **adjusted $R^2$** is more appropriate for comparing different models, especially those with differing numbers of predictors.

This completes our introduction to multiple linear regression: we now have a
model with several predictors, an interpretation for its coefficients, and
tools to judge whether the model is useful and how well it fits the data.

### Other model fit statistics: logLikelihood, AIC, and BIC

The `glance()` output also includes two additional quantities: **AIC** (Akaike Information Criterion) and **BIC** (Bayesian Information Criterion).  
Although they appear alongside the F-statistic and $R^2$, they serve a different purpose.

AIC and BIC are **not** measures of how well a single model fits the data in an absolute sense.  
Instead, they are designed for **comparing multiple competing models**, balancing goodness of fit against model complexity. Lower values indicate a preferable trade-off, but only **relative** comparisons are meaningful.

Because AIC and BIC are tools for *model selection* rather than model assessment, we do not interpret them here. They will be discussed in detail in **Module 5 (Principles of Model Building)**, where they are used to guide decisions about which predictors to include in a regression model.
